version: '3.9'
services:
  go-rest-app:
    container_name: go-rest-container
    build: .
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack

  fullstack-mysql:
    image: mariadb
    container_name: database_mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_mysql:/var/lib/mysql
    restart: always
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    env_file:
      - .env
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "9090:80"
    restart: always
    networks:
      - fullstack


volumes:
  api:
  db_mysql:

networks:
  fullstack:
    driver: bridge