name: CD Deployment
on:
  push:
    branches:
      - "master"
jobs:
  set-up-cd:
    runs-on: ubuntu-latest
    steps:
      - run: echo "starting cd for deployment"
  
  docker-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nrmadi02/nrmadi02-mini-project:latest

      - name: Start deployment to azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "starting running docker mini-project"
            docker container rm mini-project --force
            docker pull nrmadi02/nrmadi02-mini-project:latest
            docker run -p 8080:8080 --env-file ./.env --name mini-project --detach nrmadi02/nrmadi02-mini-project:latest
