name: CI Deployment

on: [pull_request]

jobs:

  testing-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Starting unit testing
      run: go test ./... -v -coverprofile cover.out && go tool cover -func ./cover.out
